# Generated by Django 6.0.2 on 2026-03-03 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_search_vector_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('tos', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookie', 'Cookie Policy'), ('dpa', 'Data Processing Agreement')], db_index=True, max_length=20)),
                ('version', models.CharField(help_text='Semantic version, e.g. "2.1.0".', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Plain-language summary of changes from previous version.')),
                ('content', models.TextField(help_text='Full policy text (Markdown supported).')),
                ('effective_date', models.DateField(help_text='Date from which this version takes effect.')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one version per policy_type should be active.')),
                ('requires_re_consent', models.BooleanField(default=False, help_text='If True, existing users must re-consent to this version.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Version',
                'verbose_name_plural': 'Policy Versions',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='When consent was withdrawn. NULL = still active.', null=True)),
                ('withdrawal_reason', models.TextField(blank=True, help_text='Optional reason for consent withdrawal.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
                ('policy_version', models.ForeignKey(help_text='The exact policy version the user consented to.', on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='compliance.policyversion')),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the team (defaults to company legal_name).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invitee.', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('recruiter', 'Recruiter'), ('viewer', 'Viewer')], default='recruiter', help_text='Role the invitee will receive upon acceptance.', max_length=20)),
                ('token', models.CharField(default='', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional personal message from the inviter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='compliance.team')),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('recruiter', 'Recruiter'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='compliance.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, help_text='Denormalised email — persists even if user is deleted.', max_length=254)),
                ('actor_role', models.CharField(blank=True, help_text='Denormalised role at time of action.', max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Token Refresh'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('PASSWORD_RESET_CONFIRM', 'Password Reset Confirm'), ('2FA_ENABLE', '2FA Enable'), ('2FA_DISABLE', '2FA Disable'), ('2FA_LOGIN', '2FA Login'), ('EMAIL_VERIFY', 'Email Verify'), ('ACCOUNT_DEACTIVATE', 'Account Deactivate'), ('ACCOUNT_REACTIVATE', 'Account Reactivate'), ('ADMIN_VERIFY_USER', 'Admin Verify User'), ('ADMIN_DEACTIVATE_USER', 'Admin Deactivate User'), ('ADMIN_TOGGLE_JOB', 'Admin Toggle Job'), ('SUBSCRIPTION_CREATE', 'Subscription Create'), ('SUBSCRIPTION_UPDATE', 'Subscription Update'), ('SUBSCRIPTION_CANCEL', 'Subscription Cancel'), ('PAYMENT_FAILED', 'Payment Failed'), ('DATA_EXPORT_REQUEST', 'Data Export Request'), ('DATA_EXPORT_DOWNLOAD', 'Data Export Download'), ('DATA_DELETION_REQUEST', 'Data Deletion Request'), ('DATA_DELETION_CANCEL', 'Data Deletion Cancel'), ('DATA_DELETION_EXECUTE', 'Data Deletion Execute'), ('CONSENT_GRANT', 'Consent Grant'), ('CONSENT_WITHDRAW', 'Consent Withdraw'), ('TEAM_CREATE', 'Team Create'), ('TEAM_INVITE', 'Team Invite'), ('TEAM_INVITE_ACCEPT', 'Team Invite Accept'), ('TEAM_INVITE_DECLINE', 'Team Invite Decline'), ('TEAM_INVITE_REVOKE', 'Team Invite Revoke'), ('TEAM_MEMBER_ROLE_CHANGE', 'Team Member Role Change'), ('TEAM_MEMBER_REMOVE', 'Team Member Remove'), ('APPLICATION_SUBMIT', 'Application Submit'), ('APPLICATION_STATUS_CHANGE', 'Application Status Change'), ('APPLICATION_WITHDRAW', 'Application Withdraw'), ('MESSAGE_SEND', 'Message Send'), ('THREAD_CREATE', 'Thread Create')], db_index=True, max_length=40)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('USER', 'User Management'), ('JOB', 'Job Management'), ('APPLICATION', 'Application'), ('MESSAGE', 'Messaging'), ('PAYMENT', 'Payment'), ('ADMIN', 'Admin Action'), ('COMPLIANCE', 'Compliance'), ('TEAM', 'Team Management'), ('SYSTEM', 'System')], db_index=True, max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of what happened.')),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text='Django model label, e.g. "accounts.User" or "jobs.JobPost".', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='Primary key of the affected resource (stringified).', max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Structured diff: {"field": {"old": ..., "new": ...}}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, help_text='Correlation ID from AuditContextMiddleware.', null=True)),
                ('checksum', models.CharField(blank=True, editable=False, help_text="SHA-256 hash of this record's canonical fields.", max_length=64)),
                ('previous_checksum', models.CharField(blank=True, editable=False, help_text='Checksum of the immediately preceding AuditLog entry (chain link).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action. NULL for system/anonymous events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='idx_audit_actor_date'), models.Index(fields=['resource_type', 'resource_id'], name='idx_audit_resource'), models.Index(fields=['action', '-created_at'], name='idx_audit_action_date'), models.Index(fields=['category', '-created_at'], name='idx_audit_category_date'), models.Index(fields=['ip_address', '-created_at'], name='idx_audit_ip_date')],
            },
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Denormalised — persists after user deletion for audit.', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('cooling_off', 'Cooling-Off Period'), ('processing', 'Processing Deletion'), ('completed', 'Completed'), ('cancelled', 'Cancelled by User'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for requesting deletion.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the user clicked the confirmation link.', null=True)),
                ('cooling_off_ends_at', models.DateTimeField(blank=True, help_text='End of the cooling-off period.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('confirmation_token', models.CharField(default='', max_length=128, unique=True)),
                ('cancellation_token', models.CharField(default='', max_length=128, unique=True)),
                ('deletion_summary', models.JSONField(blank=True, default=dict, help_text='Counts of deleted records by model.')),
                ('user', models.ForeignKey(blank=True, help_text='SET_NULL because the user row is anonymised on completion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Deletion Request',
                'verbose_name_plural': 'Data Deletion Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='idx_deletion_status_date'), models.Index(fields=['cooling_off_ends_at', 'status'], name='idx_deletion_cooloff_status')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, help_text='Storage path (R2 key or local path) of the export archive.', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this time the download link is invalid.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('download_token', models.CharField(default='', help_text='Unique token for secure download URL.', max_length=128, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export Request',
                'verbose_name_plural': 'Data Export Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_export_user_status'), models.Index(fields=['status', '-requested_at'], name='idx_export_status_date')],
            },
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['policy_type', 'is_active'], name='idx_policy_type_active'),
        ),
        migrations.AlterUniqueTogether(
            name='policyversion',
            unique_together={('policy_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['user', '-consented_at'], name='idx_consent_user_date'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['policy_version', 'withdrawn_at'], name='idx_consent_policy_withdrawn'),
        ),
        migrations.AlterUniqueTogether(
            name='consentrecord',
            unique_together={('user', 'policy_version')},
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['email', 'status'], name='idx_invite_email_status'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['team', 'status'], name='idx_invite_team_status'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'is_active'], name='idx_tm_team_active'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user', 'is_active'], name='idx_tm_user_active'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
    ]
