# Generated by Django 6.0.2 on 2026-02-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_2fa_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('Starter', 'Starter'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], default='free', max_length=50),
        ),
    ]
