# Generated by Django 6.0.2 on 2026-02-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_subscription_tier_to_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=50),
        ),
    ]
