# Generated by Django 6.0.2 on 2026-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_companyprofile_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
