# Generated by Django 6.0.2
# Adds SearchVectorField to TalentProfile and CompanyProfile for full-text search.

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
    ]
