# Generated by Django 6.0.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, help_text='The raw search query entered by the user.', max_length=500)),
                ('normalized_query', models.CharField(blank=True, db_index=True, help_text='Lowercased, stripped query for aggregation.', max_length=500)),
                ('entity_type', models.CharField(choices=[('jobs', 'Jobs'), ('talent', 'Talent Profiles'), ('companies', 'Companies'), ('all', 'Unified Search')], db_index=True, default='all', max_length=20)),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Number of results returned for this query.')),
                ('clicked_result_id', models.PositiveIntegerField(blank=True, help_text='PK of the result the user clicked on.', null=True)),
                ('clicked_position', models.PositiveSmallIntegerField(blank=True, help_text='1-based position of the clicked result in the list.', null=True)),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='Snapshot of active filters at search time.')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Server-side response time in milliseconds.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous searches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['normalized_query', '-created_at'], name='idx_search_norm_query_date'),
                    models.Index(fields=['entity_type', '-created_at'], name='idx_search_entity_date'),
                    models.Index(fields=['user', '-created_at'], name='idx_search_user_date'),
                ],
            },
        ),
    ]
