# Generated by Django 6.0.2
# Creates GIN indexes on search_vector columns and ensures pg_trgm + unaccent
# extensions are available for trigram fuzzy matching.
#
# NeonDB (production) already has pg_trgm 1.6 and unaccent 1.1 provisioned.
# CREATE EXTENSION IF NOT EXISTS is safe to run — no-ops if already present.

from django.db import migrations


class Migration(migrations.Migration):

    # CONCURRENTLY indexes cannot be created inside a transaction.
    atomic = False

    dependencies = [
        ('jobs', '0005_search_vector_field'),
        ('accounts', '0008_search_vector_fields'),
        ('search', '0001_initial'),
    ]

    operations = [
        # ─── Extensions ──────────────────────────────────────────────────
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS pg_trgm;',
            reverse_sql='DROP EXTENSION IF EXISTS pg_trgm;',
        ),
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS unaccent;',
            reverse_sql='DROP EXTENSION IF EXISTS unaccent;',
        ),

        # ─── GIN indexes on SearchVectorField columns ────────────────────
        # These enable O(log n) full-text lookups regardless of table size.
        migrations.RunSQL(
            sql='''
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_jobpost_search_vector
                ON jobs_jobpost USING GIN (search_vector);
            ''',
            reverse_sql='DROP INDEX IF EXISTS idx_jobpost_search_vector;',
            state_operations=[],
        ),
        migrations.RunSQL(
            sql='''
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_talentprofile_search_vector
                ON accounts_talentprofile USING GIN (search_vector);
            ''',
            reverse_sql='DROP INDEX IF EXISTS idx_talentprofile_search_vector;',
            state_operations=[],
        ),
        migrations.RunSQL(
            sql='''
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_companyprofile_search_vector
                ON accounts_companyprofile USING GIN (search_vector);
            ''',
            reverse_sql='DROP INDEX IF EXISTS idx_companyprofile_search_vector;',
            state_operations=[],
        ),

        # ─── GIN trigram indexes for fuzzy/typo-tolerant search ──────────
        # These speed up TrigramSimilarity lookups used in the fallback path.
        migrations.RunSQL(
            sql='''
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_jobpost_title_trgm
                ON jobs_jobpost USING GIN (title gin_trgm_ops);
            ''',
            reverse_sql='DROP INDEX IF EXISTS idx_jobpost_title_trgm;',
            state_operations=[],
        ),
        migrations.RunSQL(
            sql='''
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_jobpost_location_trgm
                ON jobs_jobpost USING GIN (location gin_trgm_ops);
            ''',
            reverse_sql='DROP INDEX IF EXISTS idx_jobpost_location_trgm;',
            state_operations=[],
        ),
        migrations.RunSQL(
            sql='''
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_talentprofile_bio_trgm
                ON accounts_talentprofile USING GIN (bio gin_trgm_ops);
            ''',
            reverse_sql='DROP INDEX IF EXISTS idx_talentprofile_bio_trgm;',
            state_operations=[],
        ),
        migrations.RunSQL(
            sql='''
                CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_companyprofile_legalname_trgm
                ON accounts_companyprofile USING GIN (legal_name gin_trgm_ops);
            ''',
            reverse_sql='DROP INDEX IF EXISTS idx_companyprofile_legalname_trgm;',
            state_operations=[],
        ),
    ]
