web: daphne -b 0.0.0.0 -p $PORT talentorbit.asgi:application
worker: celery -A talentorbit worker -l info -Q default,emails,notifications,dlq --concurrency 2 -O fair
beat: celery -A talentorbit beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
