{{- if .Values.api.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "talentorbit.fullname" . }}-api
  namespace: {{ include "talentorbit.namespace" . }}
  labels:
    {{- include "talentorbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if .Values.api.pdb.minAvailable }}
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  {{- else if .Values.api.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.api.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "talentorbit.componentLabels" (dict "root" . "component" "api") | nindent 6 }}
{{- end }}
