# Generated by Django 6.0.2 on 2026-03-03 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0005_search_vector_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users_1d', models.PositiveIntegerField(default=0)),
                ('active_users_7d', models.PositiveIntegerField(default=0)),
                ('active_users_30d', models.PositiveIntegerField(default=0)),
                ('talent_count', models.PositiveIntegerField(default=0)),
                ('company_count', models.PositiveIntegerField(default=0)),
                ('total_open_jobs', models.PositiveIntegerField(default=0)),
                ('new_jobs_posted', models.PositiveIntegerField(default=0)),
                ('jobs_closed', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('new_applications', models.PositiveIntegerField(default=0)),
                ('offers_extended', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('total_searches', models.PositiveIntegerField(default=0)),
                ('avg_search_results', models.FloatField(blank=True, null=True)),
                ('total_recommendation_requests', models.PositiveIntegerField(default=0)),
                ('avg_recommendation_ctr', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Platform Metrics',
                'verbose_name_plural': 'Daily Platform Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('artifact_data', models.BinaryField()),
                ('metadata', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Model Artifact',
                'ordering': ['-version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('parsed_skills', models.JSONField(default=list, help_text='[{name, canonical_name, confidence, source}]')),
                ('parsed_experience', models.JSONField(default=list, help_text='[{title, company, start, end, months, description}]')),
                ('parsed_education', models.JSONField(default=list, help_text='[{degree, institution, field, year}]')),
                ('total_experience_years', models.FloatField(blank=True, null=True)),
                ('generated_bio', models.TextField(blank=True, max_length=500)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('parser_version', models.CharField(default='spacy_v1', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
                ('source_file_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parsed Resume',
            },
        ),
        migrations.CreateModel(
            name='PlatformBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=150)),
                ('value', models.FloatField()),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Benchmark',
                'unique_together': {('metric_name', 'industry', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_jobs', models.JSONField(default=list)),
                ('algorithm_version', models.CharField(max_length=50)),
                ('weights_used', models.JSONField(default=dict)),
                ('latency_ms', models.PositiveIntegerField()),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, help_text='e.g. Programming, Design, Management', max_length=100)),
                ('aliases', models.JSONField(default=list, help_text='Alternative names: ["React.js", "ReactJS"]')),
                ('embedding_vector', models.BinaryField(blank=True, help_text='Serialised numpy array for vector search', null=True)),
                ('proficiency_levels', models.JSONField(blank=True, default=list, help_text='Proficiency descriptors: [{level, label, description}]')),
                ('is_verified', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent skill for hierarchical taxonomy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='intelligence.skilltaxonomy')),
                ('related_skills', models.ManyToManyField(blank=True, help_text='Frequently co-occurring skills', to='intelligence.skilltaxonomy')),
            ],
            options={
                'verbose_name': 'Skill Taxonomy',
                'verbose_name_plural': 'Skill Taxonomy',
                'ordering': ['-usage_count', 'canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='HiringFunnelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('applications', models.PositiveIntegerField(default=0)),
                ('reviewing', models.PositiveIntegerField(default=0)),
                ('shortlisted', models.PositiveIntegerField(default=0)),
                ('interviewing', models.PositiveIntegerField(default=0)),
                ('offered', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('withdrawn', models.PositiveIntegerField(default=0)),
                ('avg_time_to_review_hours', models.FloatField(blank=True, null=True)),
                ('avg_time_to_shortlist_hours', models.FloatField(blank=True, null=True)),
                ('avg_time_to_offer_hours', models.FloatField(blank=True, null=True)),
                ('avg_time_to_hire_hours', models.FloatField(blank=True, null=True)),
                ('avg_match_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_snapshots', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='NULL = aggregate for all company jobs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_snapshots', to='jobs.jobpost')),
            ],
            options={
                'verbose_name': 'Hiring Funnel Snapshot',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', '-date', 'period'], name='idx_funnel_company_date'), models.Index(fields=['job', '-date'], name='idx_funnel_job_date')],
                'unique_together': {('company', 'job', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SourceAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Direct (Job Board)'), ('search', 'Search'), ('recommendation', 'Recommendation Engine'), ('external', 'External Referral'), ('notification', 'Notification')], db_index=True, max_length=20)),
                ('search_query', models.CharField(blank=True, max_length=500)),
                ('converted_to_application', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_attributions', to='jobs.jobpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Source Attribution',
                'indexes': [models.Index(fields=['job', 'source', '-created_at'], name='idx_source_job_src_date')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('click', 'Search Click'), ('save', 'Saved'), ('apply', 'Applied'), ('unsave', 'Unsaved')], db_index=True, max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_interactions', to='jobs.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interaction',
                'indexes': [models.Index(fields=['user', 'job', 'interaction_type'], name='idx_intel_user_job_type'), models.Index(fields=['user', '-created_at'], name='idx_intel_user_date'), models.Index(fields=['job', 'interaction_type'], name='idx_intel_job_type')],
            },
        ),
    ]
