# Generated by Django 6.0.2 on 2026-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('readTime', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=50)),
                ('img', models.URLField(max_length=500)),
                ('alt', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
