# Generated by Django 6.0.2 on 2026-03-03 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_search_vector_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIChangelog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='e.g. v4.0.2', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Markdown-supported description of changes.')),
                ('change_type', models.CharField(choices=[('major', 'Major Release'), ('minor', 'Minor Release'), ('patch', 'Patch'), ('deprecation', 'Deprecation'), ('security', 'Security Fix')], default='patch', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_changelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Changelog',
                'verbose_name_plural': 'API Changelog Entries',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='HTTPS endpoint URL that receives POST payloads.', max_length=500)),
                ('events', models.JSONField(default=list, help_text='List of event type strings this endpoint listens to.')),
                ('signing_secret_signed', models.CharField(editable=False, help_text='Signer-protected webhook signing secret.', max_length=256)),
                ('signing_secret_prefix', models.CharField(editable=False, help_text='First 12 chars for display.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Consecutive delivery failures. Resets on success.')),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='accounts.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(default=dict, help_text='Full JSON payload delivered to the endpoint.')),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='HTTP status code from the endpoint response.', null=True)),
                ('response_body', models.TextField(blank=True, help_text='First 2KB of the endpoint response body.')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Round-trip time in milliseconds.', null=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='Retry attempt number (1 = first try).')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed (timeout, DNS, etc.).')),
                ('is_success', models.BooleanField(db_index=True, default=False, help_text='True if status_code is 2xx.')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='developer.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-friendly key label.', max_length=100)),
                ('key_hash', models.CharField(editable=False, help_text='SHA-256 of the full API key.', max_length=64, unique=True)),
                ('prefix', models.CharField(editable=False, help_text='First 12 chars of the key (for UI identification).', max_length=20)),
                ('scopes', models.JSONField(default=list, help_text='List of permission scope strings.')),
                ('ip_allowlist', models.JSONField(default=list, help_text='List of allowed IPv4/IPv6 CIDRs. Empty = unrestricted.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('daily_usage', models.JSONField(default=list, help_text='Rolling 7-day usage counts for sparkline rendering.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Null = never expires.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='idx_apikey_hash'), models.Index(fields=['company', 'is_active'], name='idx_apikey_company_active')],
            },
        ),
        migrations.CreateModel(
            name='OAuthApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Application display name.', max_length=150)),
                ('client_id', models.CharField(editable=False, help_text='Public OAuth client identifier.', max_length=40, unique=True)),
                ('client_secret_hash', models.CharField(editable=False, help_text='SHA-256 of the client secret.', max_length=64)),
                ('client_secret_prefix', models.CharField(editable=False, help_text='First 12 chars of the client secret (for UI).', max_length=20)),
                ('redirect_uris', models.JSONField(default=list, help_text='List of allowed redirect URI strings.')),
                ('scopes', models.JSONField(default=list, help_text='List of OAuth scope strings.')),
                ('logo_initials', models.CharField(blank=True, help_text='1-2 character initials for logo placeholder.', max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('authorized_users_count', models.PositiveIntegerField(default=0, help_text='Cached count of users who have authorized this app.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_applications', to='accounts.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_oauth_apps', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_oauth_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Application',
                'verbose_name_plural': 'OAuth Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_id'], name='idx_oauth_client_id'), models.Index(fields=['company', 'status'], name='idx_oauth_company_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(fields=('company', 'url'), name='uq_webhook_company_url'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', '-delivered_at'], name='idx_delivery_endpoint_date'),
        ),
    ]
