# Generated by Django 6.0.2 on 2026-03-03 17:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_search_vector_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_anonymous', models.BooleanField(default=True, help_text='If True, author identity is hidden from public-facing APIs.')),
                ('rating_culture', models.PositiveIntegerField(help_text='Culture & Values (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_growth', models.PositiveIntegerField(help_text='Career Growth (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_compensation', models.PositiveIntegerField(help_text='Compensation & Benefits (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_management', models.PositiveIntegerField(help_text='Senior Management (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_worklife', models.PositiveIntegerField(help_text='Work-Life Balance (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('headline', models.CharField(blank=True, help_text='Optional one-line summary / quote.', max_length=200)),
                ('pros', models.TextField(help_text='What the reviewer liked about the company.')),
                ('cons', models.TextField(help_text='What the reviewer disliked or areas for improvement.')),
                ('employment_status', models.CharField(choices=[('current', 'Current Employee'), ('former', 'Former Employee'), ('contractor', 'Contractor')], default='current', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('role_title', models.CharField(blank=True, max_length=200)),
                ('tenure_months', models.PositiveIntegerField(blank=True, help_text='How long at the company in months.', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set to True when author email domain matches company domain.')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Review',
                'verbose_name_plural': 'Company Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Official company response text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_response', to='reviews.companyreview')),
            ],
            options={
                'verbose_name': 'Company Review Response',
                'verbose_name_plural': 'Company Review Responses',
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.companyreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Helpful Vote',
                'verbose_name_plural': 'Review Helpful Votes',
            },
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['company', 'moderation_status', '-created_at'], name='idx_review_company_status'),
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['author', 'company'], name='idx_review_author_company'),
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['moderation_status'], name='idx_review_mod_status'),
        ),
        migrations.AddConstraint(
            model_name='companyreview',
            constraint=models.UniqueConstraint(fields=('author', 'company'), name='uq_review_author_company'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('user', 'review')},
        ),
    ]
