# Generated by Django 6.0.2 on 2026-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=500)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
