# Generated by Django 6.0.2 on 2026-02-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, help_text='External course URL (opens in new tab)', max_length=500),
        ),
    ]
