# Generated by Django 6.0.2 on 2026-03-03 17:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_course_slugs(apps, schema_editor):
    """Generate unique slugs for existing Course rows based on their title."""
    Course = apps.get_model('courses', 'Course')
    seen = set()
    for course in Course.objects.all():
        base = slugify(course.title) or f'course-{course.pk}'
        slug = base
        counter = 1
        while slug in seen:
            slug = f'{base}-{counter}'
            counter += 1
        seen.add(slug)
        course.slug = slug
        course.save(update_fields=['slug'])



class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within the course (0-indexed).')),
                ('is_preview', models.BooleanField(default=False, help_text='If True, this module is accessible without enrollment (free preview).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='1–5 star rating.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Written review.', max_length=5000)),
                ('is_verified_enrollment', models.BooleanField(default=False, help_text='Auto-set to True if user has an active/completed enrollment.')),
                ('is_approved', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_notes', models.TextField(blank=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text / Article'), ('markdown', 'Markdown'), ('code', 'Interactive Code'), ('quiz', 'Quiz / Assessment'), ('assignment', 'Assignment'), ('external', 'External Link')], db_index=True, default='text', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within the module.')),
                ('text_content', models.TextField(blank=True, help_text='Rich text or Markdown content for text/markdown lessons.')),
                ('video_url', models.URLField(blank=True, help_text='URL to the video file (R2, Cloudflare Stream, or external).')),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Video duration in seconds (for progress tracking).', null=True)),
                ('video_thumbnail_url', models.URLField(blank=True)),
                ('video_transcript', models.TextField(blank=True, help_text='Full video transcript (for search indexing and accessibility).')),
                ('code_language', models.CharField(blank=True, help_text='Programming language for code lessons (e.g. "python", "javascript").', max_length=50)),
                ('code_starter', models.TextField(blank=True, help_text='Starter code template provided to the student.')),
                ('code_solution', models.TextField(blank=True, help_text='Reference solution (shown after completion).')),
                ('code_test_cases', models.JSONField(blank=True, default=list, help_text='[{"input": "...", "expected_output": "...", "description": "..."}]')),
                ('quiz_config', models.JSONField(blank=True, default=dict, help_text='{"assessment_id": ..., "passing_score": 70, "max_attempts": 3}')),
                ('external_url', models.URLField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=5, help_text='Estimated time to complete this lesson.')),
                ('is_preview', models.BooleanField(default=False, help_text='Accessible without enrollment (free preview lesson).')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Must be completed for course completion certificate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='courses/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xlsx', 'xls', 'zip', 'tar', 'gz', 'png', 'jpg', 'jpeg', 'gif', 'svg', 'webp', 'py', 'js', 'ts', 'jsx', 'tsx', 'html', 'css', 'json', 'yaml', 'yml'])])),
                ('file_size_bytes', models.PositiveIntegerField(default=0, help_text='Auto-populated on save.')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lesson Attachment',
                'verbose_name_plural': 'Lesson Attachments',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('video_position_seconds', models.PositiveIntegerField(default=0, help_text='Last playback position (for resume functionality).')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of attempts (for quizzes and code challenges).')),
                ('best_score', models.DecimalField(blank=True, decimal_places=2, help_text='Best score achieved (0–100 for quizzes).', max_digits=5, null=True)),
                ('last_submission', models.JSONField(blank=True, default=dict, help_text='Last submitted answer/code for reference.')),
                ('notes', models.TextField(blank=True, help_text="User's personal notes for this lesson.")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
                'ordering': ['lesson__position'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_coming_soon',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
        migrations.AddField(
            model_name='course',
            name='access_level',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium (requires subscription)')], db_index=True, default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='completion_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin/instructor who created this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='', help_text='Full course description (Markdown supported).'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total estimated duration in minutes (auto-computed from lessons).'),
        ),
        migrations.AddField(
            model_name='course',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL for externally-hosted courses (opens in new tab). If set, the course acts as a link rather than hosted content.'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_external',
            field=models.BooleanField(default=False, help_text='True if this course is hosted externally.'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], db_index=True, default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='max_enrollments',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of enrollments. NULL = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Courses that should be completed before this one.', related_name='dependent_courses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video_url',
            field=models.URLField(blank=True, help_text='URL to a preview/trailer video (R2 or external).'),
        ),
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='required_subscription_tier',
            field=models.CharField(blank=True, help_text='Minimum subscription tier required (e.g. "premium", "professional"). Empty = no tier restriction beyond access_level.', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, help_text='One-liner for cards and search results.', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.JSONField(default=list, help_text='Skills taught in this course: ["Python", "Django", "REST APIs"]'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=280),
        ),
        migrations.RunPython(
            populate_course_slugs,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE courses_course ADD CONSTRAINT courses_course_slug_key UNIQUE (slug);',
            reverse_sql='ALTER TABLE courses_course DROP CONSTRAINT IF EXISTS courses_course_slug_key;',
            state_operations=[
                migrations.AlterField(
                    model_name='course',
                    name='slug',
                    field=models.SlugField(default='', max_length=280, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(default=list, help_text='Searchable tags: ["web-development", "backend"]'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='version',
            field=models.CharField(default='1.0', help_text='Content version (for tracking updates to published courses).', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (e.g. Lucide icon name or emoji)', max_length=100)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within parent category.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.coursecategory')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall course completion percentage (0.00–100.00).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('total_time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Cumulative time spent on all lessons.')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_name', models.CharField(max_length=255)),
                ('holder_email', models.EmailField(max_length=254)),
                ('course_title', models.CharField(max_length=255)),
                ('course_version', models.CharField(max_length=20)),
                ('instructor_names', models.JSONField(default=list, help_text='Instructor names at time of issuance.')),
                ('completion_date', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=1, help_text='Total hours spent on the course.', max_digits=6)),
                ('skills_earned', models.JSONField(default=list, help_text='Skills validated by completing this course.')),
                ('signature', models.CharField(editable=False, help_text='HMAC-SHA256 signature for verification.', max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.TextField(blank=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.courseenrollment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='instructors/avatars/')),
                ('credentials', models.JSONField(blank=True, default=list, help_text='List of credentials: [{"title": "...", "issuer": "...", "year": 2024}]')),
                ('website_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by TalentOrbit team.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Platform user. NULL for external instructors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Instructor',
                'verbose_name_plural': 'Course Instructors',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.courseinstructor'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', '-published_at'], name='idx_course_status_pub'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='idx_course_cat_status'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'status'], name='idx_course_level_status'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['access_level', 'status'], name='idx_course_access_status'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-average_rating', 'status'], name='idx_course_rating_status'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-enrollment_count'], name='idx_course_enrollment_ct'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='unlock_after_module',
            field=models.ForeignKey(blank=True, help_text='Module that must be completed before this one is accessible.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='last_lesson',
            field=models.ForeignKey(blank=True, help_text='Last lesson the user accessed (for "Continue" button).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.courseenrollment'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson'),
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['parent', 'position'], name='idx_coursecat_parent_pos'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecategory',
            unique_together={('parent', 'slug')},
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'position'], name='idx_module_course_pos'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'position')},
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-created_at'], name='idx_creview_course_date'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-helpful_count'], name='idx_creview_course_helpful'),
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'position'], name='idx_lesson_module_pos'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='idx_lesson_type'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'position')},
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'status'], name='idx_enrollment_user_status'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'status'], name='idx_enrollment_course_status'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', '-last_accessed_at'], name='idx_enrollment_user_access'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='idx_progress_enroll_done'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
    ]
