# Generated by Django 6.0.2 on 2026-03-04 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_search_vector_field'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status', '-created_at'], name='idx_invoice_cust_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='idx_invoice_status_due'),
        ),
        migrations.AddIndex(
            model_name='sponsoredjobcampaign',
            index=models.Index(fields=['company', 'status'], name='idx_campaign_company_status'),
        ),
        migrations.AddIndex(
            model_name='sponsoredjobcampaign',
            index=models.Index(fields=['status', 'ends_at'], name='idx_campaign_status_ends'),
        ),
        migrations.AddIndex(
            model_name='sponsoredjobcampaign',
            index=models.Index(fields=['status', 'amount_spent', 'total_budget'], name='idx_campaign_budget'),
        ),
    ]
