# Generated by Django 6.0.2 on 2026-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior (1-2 years)'), ('mid', 'Mid-Level (3-5 years)'), ('senior', 'Senior (5-8 years)'), ('lead', 'Lead / Director (8+ years)')], default='mid', max_length=20),
        ),
    ]
