# Generated by Django 6.0.2 on 2026-03-02 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_experience_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['company', 'status'], name='idx_job_company_status'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['-created_at', 'status'], name='idx_job_created_status'),
        ),
    ]
