# Generated by Django 6.0.2 on 2026-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobpost_status_jobpost_idx_job_company_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('offered', 'Offer Extended'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Applicant')], db_index=True, default='pending', max_length=20),
        ),
    ]
