# Generated by Django 6.0.2
# Adds SearchVectorField to JobPost for full-text search.

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
    ]
