# Generated by Django 6.0.2 on 2026-03-02 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=10000),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'read'], name='idx_msg_thread_read'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'sent_at'], name='idx_msg_thread_sent'),
        ),
    ]
