# Generated by Django 6.0.2 on 2026-03-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the recipient read this message.', null=True),
        ),
    ]
